- type: string
  key: 'name'
  validation:
  - type: regex
    expression: '^[a-zA-Z_0-9]{4,}$'
  default: 'abcd'
- type: path
  key: 'input'
  default: './samples/'
- type: flag
  key: 'with_images'
