#!python3
from py2g_utils.arguments import FileArgumentParser
import os.path as osp

parser = FileArgumentParser('./arguments/base.yaml', './arguments/process.yaml', basepath=osp.split(osp.abspath(__file__))[0])
arguments = parser.parse()

for key in arguments.keys():
    argument = arguments.__getattribute__(key)
    if type(argument) == list:
        print("{}:".format(key))
        for v in argument:
            print("\t{}".format(v))
    else:
        print("{}: {}".format(key, argument))
